import { Icountry } from "../model/country";


// export const COUNTRIES_META_DATA : Array<Icountry> = []
 export   const COUNTRIES_META_DATA : Array<Icountry> = [
        {'name': 'Aruba', 
        'currency': 'Aruban Florin', 
        'currency_code': 'AWG'
        },
         {'name': 'Albania', 
          'currency': 'Lek',
          'currency_code': 'ALL'
         }, 
         {
         'name': 'United Arab Emirates',
          'currency': 'UAE Dirham', 
          'currency_code': 'AED'
        }, 
        {
            'name': 'Argentina', 
            'currency': 'Argentine Peso',
            'currency_code': 'ARS'
        },
         {
            'name': 'Armenia', 
            'currency': 'Armenian Dram',
             'currency_code': 'AMD'
            }, 
        {
            'name': 'Australia', 
            'currency': 'Australian Dollar',
             'currency_code': 'AUD'
            }, 
            {'name': 'Burundi', 'currency': 'Burundi Franc', 'currency_code': 'BIF'}, 
            {'name': 'Bangladesh', 'currency': 'Taka', 'currency_code': 'BDT'}, 
            {'name': 'Bahrain', 'currency': 'Bahraini Dinar', 'currency_code': 'BHD'}, 
            
            
            {'name': 'Bahamas', 'currency': 'Bahamian Dollar', 'currency_code': 'BSD'},
             {'name': 'Belize', 'currency': 'Belize Dollar', 'currency_code': 'BZD'}, 
             {'name': 'Bermuda', 'currency': 'Bermudian Dollar', 'currency_code': 'BMD'},
              {'name': 'Bolivia, Plurinational State of', 'currency': 'Boliviano', 'currency_code': 'BOB'},
               {'name': 'Barbados', 'currency': 'Barbados Dollar', 'currency_code': 'BBD'},
         {'name': 'Brunei Darussalam', 'currency': 'Brunei Dollar', 'currency_code': 'BND'},
        {'name': 'Bhutan', 'currency': 'Ngultrum', 'currency_code': 'BTN'},
         {'name': 'Botswana', 'currency': 'Pula', 'currency_code': 'BWP'}, 
          {'name': 'Canada', 'currency': 'Canadian Dollar', 'currency_code': 'CAD'}, 
         {'name': 'Switzerland', 'currency': 'Swiss Franc', 'currency_code': 'CHF'},
          {'name': 'Chile', 'currency': 'Chilean Peso', 'currency_code': 'CLP'},
        {'name': 'China', 'currency': 'Yuan Renminbi', 'currency_code': 'CNY'},
         {'name': 'Colombia', 'currency': 'Colombian Peso', 'currency_code': 'COP'}, 
         {'name': 'Comoros', 'currency': 'Comoro Franc', 'currency_code': 'KMF'},
          {'name': 'Cabo Verde', 'currency': 'Cabo Verde Escudo', 'currency_code': 'CVE'},
           {'name': 'Costa Rica', 'currency': 'Costa Rican Colon', 'currency_code': 'CRC'},
            {'name': 'Cuba', 'currency': 'Cuban Peso', 'currency_code': 'CUP'}, 
            {'name': 'Cayman Islands', 'currency': 'Cayman Islands Dollar', 'currency_code': 'KYD'},
             {'name': 'Czechia', 'currency': 'Czech Koruna', 'currency_code': 'CZK'},
              {'name': 'Djibouti', 'currency': 'Djibouti Franc', 'currency_code': 'DJF'}, 
              {'name': 'Denmark', 'currency': 'Danish Krone', 'currency_code': 'DKK'},
               {'name': 'Dominican Republic', 'currency': 'Dominican Peso', 'currency_code': 'DOP'},
                {'name': 'Algeria', 'currency': 'Algerian Dinar', 'currency_code': 'DZD'}, 
                {'name': 'Egypt', 'currency': 'Egyptian Pound', 'currency_code': 'EGP'}, 
                {'name': 'Eritrea', 'currency': 'Nakfa', 'currency_code': 'ERN'},
                 {'name': 'Fiji', 'currency': 'Fiji Dollar', 'currency_code': 'FJD'}, 
                 {'name': 'Falkland Islands (Malvinas)', 'currency': 'Falkland Islands Pound', 'currency_code': 'FKP'}, 
                 {'name': 'United Kingdom', 'currency': 'Pound Sterling', 'currency_code': 'GBP'},
                 {'name': 'Gibraltar', 'currency': 'Gibraltar Pound', 'currency_code': 'GIP'},
                 {'name': 'Guinea', 'currency': 'Guinea Franc', 'currency_code': 'GNF'}, 
                 {'name': 'Gambia', 'currency': 'Dalasi', 'currency_code': 'GMD'},
                  {'name': 'Guatemala', 'currency': 'Quetzal', 'currency_code': 'GTQ'}, 
                  {'name': 'Guyana', 'currency': 'Guyana Dollar', 'currency_code': 'GYD'}, 
                  {'name': 'Hong Kong', 'currency': 'Hong Kong Dollar', 'currency_code': 'HKD'}, 
                  {'name': 'Honduras', 'currency': 'Lempira', 'currency_code': 'HNL'},
                   {'name': 'Croatia', 'currency': 'Kuna', 'currency_code': 'HRK'},
                    {'name': 'Haiti', 'currency': 'Gourde', 'currency_code': 'HTG'}, 
                    {'name': 'Hungary', 'currency': 'Forint', 'currency_code': 'HUF'},
                     {'name': 'Indonesia', 'currency': 'Rupiah', 'currency_code': 'IDR'},
                      {'name': 'India', 'currency': 'Indian Rupee', 'currency_code': 'INR'}, 
                      {'name': 'Iran, Islamic Republic of', 'currency': 'Iranian Rial', 'currency_code': 'IRR'}, 
                      {'name': 'Iraq', 'currency': 'Iraqi Dinar', 'currency_code': 'IQD'},
                       {'name': 'Iceland', 'currency': 'Iceland Krona', 'currency_code': 'ISK'},
                        {'name': 'Israel', 'currency': 'New Israeli Sheqel', 'currency_code': 'ILS'}, 
                        {'name': 'Jamaica', 'currency': 'Jamaican Dollar', 'currency_code': 'JMD'}, 
                        {'name': 'Jordan', 'currency': 'Jordanian Dinar', 'currency_code': 'JOD'},
                         {'name': 'Japan', 'currency': 'Yen', 'currency_code': 'JPY'},
                         {'name': 'Kazakhstan', 'currency': 'Tenge', 'currency_code': 'KZT'},
                          {'name': 'Kenya', 'currency': 'Kenyan Shilling', 'currency_code': 'KES'}, 
                          {'name': 'Kyrgyzstan', 'currency': 'Som', 'currency_code': 'KGS'},
                           {'name': 'Cambodia', 'currency': 'Riel', 'currency_code': 'KHR'}, 
                           {'name': 'Korea, Republic of', 'currency': 'Won', 'currency_code': 'KRW'}, 
                           {'name': 'Kuwait', 'currency': 'Kuwaiti Dinar', 'currency_code': 'KWD'},
                            {'name': "Lao People's Democratic Republic", 'currency': 'Kip', 'currency_code': 'LAK'}, 
                            {'name': 'Lebanon', 'currency': 'Lebanese Pound', 'currency_code': 'LBP'},
                             {'name': 'Liberia', 'currency': 'Liberian Dollar', 'currency_code': 'LRD'},
                              {'name': 'Libya', 'currency': 'Libyan Dinar', 'currency_code': 'LYD'},
                               {'name': 'Sri Lanka', 'currency': 'Sri Lanka Rupee', 'currency_code': 'LKR'},
                                {'name': 'Lesotho', 'currency': 'Loti', 'currency_code': 'LSL'}, 
                                {'name': 'Macao', 'currency': 'Pataca', 'currency_code': 'MOP'},
                                 {'name': 'Morocco', 'currency': 'Moroccan Dirham', 'currency_code': 'MAD'}, 
        {'name': 'Moldova, Republic of', 'currency': 'Moldovan Leu', 'currency_code': 'MDL'},
         {'name': 'Maldives', 'currency': 'Rufiyaa', 'currency_code': 'MVR'}, 
         {'name': 'Mexico', 'currency': 'Mexican Peso', 'currency_code': 'MXN'},
          {'name': 'North Macedonia', 'currency': 'Denar', 'currency_code': 'MKD'}, 
          {'name': 'Myanmar', 'currency': 'Kyat', 'currency_code': 'MMK'}, 
          {'name': 'Mongolia', 'currency': 'Tugrik', 'currency_code': 'MNT'}, 
          {'name': 'Mauritania', 'currency': 'Ouguiya', 'currency_code': 'MRO'}, 
          {'name': 'Mauritius', 'currency': 'Mauritius Rupee', 'currency_code': 'MUR'},
           {'name': 'Malawi', 'currency': 'Malawi Kwacha', 'currency_code': 'MWK'}, 
           {'name': 'Malaysia', 'currency': 'Malaysian Ringgit', 'currency_code': 'MYR'},
            {'name': 'Namibia', 'currency': 'Namibia Dollar', 'currency_code': 'NAD'}, 
            {'name': 'Nigeria', 'currency': 'Naira', 'currency_code': 'NGN'},
             {'name': 'Nicaragua', 'currency': 'Cordoba Oro', 'currency_code': 'NIO'}, 
             {'name': 'Norway', 'currency': 'Norwegian Krone', 'currency_code': 'NOK'}, 
             {'name': 'Nepal', 'currency': 'Nepalese Rupee', 'currency_code': 'NPR'}, 
             {'name': 'New Zealand', 'currency': 'New Zealand Dollar', 'currency_code': 'NZD'},
              {'name': 'Oman', 'currency': 'Rial Omani', 'currency_code': 'OMR'}, 
              {'name': 'Pakistan', 'currency': 'Pakistan Rupee', 'currency_code': 'PKR'}, 
              {'name': 'Peru', 'currency': 'Sol', 'currency_code': 'PEN'}, 
              {'name': 'Philippines', 'currency': 'Philippine Peso', 'currency_code': 'PHP'},
               {'name': 'Papua New Guinea', 'currency': 'Kina', 'currency_code': 'PGK'}, 
               {'name': "Korea, Democratic People's Republic of", 'currency': 'North Korean Won', 'currency_code': 'KPW'},
                {'name': 'Paraguay', 'currency': 'Guarani', 'currency_code': 'PYG'}, 
                {'name': 'Qatar', 'currency': 'Qatari Rial', 'currency_code': 'QAR'}, 
                {'name': 'Russian Federation', 'currency': 'Russian Ruble', 'currency_code': 'RUB'},
                 {'name': 'Rwanda', 'currency': 'Rwanda Franc', 'currency_code': 'RWF'}, 
                 {'name': 'Saudi Arabia', 'currency': 'Saudi Riyal', 'currency_code': 'SAR'},
                  {'name': 'Singapore', 'currency': 'Singapore Dollar', 'currency_code': 'SGD'}, 
                  {'name': 'Saint Helena, Ascension and Tristan da Cunha', 'currency': 'Saint Helena Pound', 'currency_code': 'SHP'},
                   {'name': 'Solomon Islands', 'currency': 'Solomon Islands Dollar', 'currency_code': 'SBD'},
                    {'name': 'Sierra Leone', 'currency': 'Leone', 'currency_code': 'SLL'},
                     {'name': 'El Salvador', 'currency': 'El Salvador Colon', 'currency_code': 'SVC'},
                      {'name': 'Somalia', 'currency': 'Somali Shilling', 'currency_code': 'SOS'},
                       {'name': 'South Sudan', 'currency': 'South Sudanese Pound', 'currency_code': 'SSP'}, 
                       {'name': 'Sao Tome and Principe', 'currency': 'Dobra', 'currency_code': 'STD'},
                        {'name': 'Sweden', 'currency': 'Swedish Krona', 'currency_code': 'SEK'},
                         {'name': 'Eswatini', 'currency': 'Lilangeni', 'currency_code': 'SZL'}, 
                         {'name': 'Seychelles', 'currency': 'Seychelles Rupee', 'currency_code': 'SCR'}, 
                         {'name': 'Syrian Arab Republic', 'currency': 'Syrian Pound', 'currency_code': 'SYP'},
                          {'name': 'Thailand', 'currency': 'Baht', 'currency_code': 'THB'}, 
        {'name': 'Tonga', 'currency': 'Paanga', 'currency_code': 'TOP'},
         {'name': 'Trinidad and Tobago', 'currency': 'Trinidad and Tobago Dollar', 'currency_code': 'TTD'},
          {'name': 'Tunisia', 'currency': 'Tunisian Dinar', 'currency_code': 'TND'}, 
          {'name': 'Tanzania, United Republic of', 'currency': 'Tanzanian Shilling', 'currency_code': 'TZS'},
           {'name': 'Uganda', 'currency': 'Uganda Shilling', 'currency_code': 'UGX'},
            {'name': 'Uruguay', 'currency': 'Peso Uruguayo', 'currency_code': 'UYU'}, 
            {'name': 'United States', 'currency': 'US Dollar', 'currency_code': 'USD'},
             {'name': 'Uzbekistan', 'currency': 'Uzbekistan Sum', 'currency_code': 'UZS'}, 
             {'name': 'Viet Nam', 'currency': 'Dong', 'currency_code': 'VND'}, 
             {'name': 'Vanuatu', 'currency': 'Vatu', 'currency_code': 'VUV'},
              {'name': 'Samoa', 'currency': 'Tala', 'currency_code': 'WST'}, 
              {'name': 'South Africa', 'currency': 'Rand', 'currency_code':'ZAR'}];

